apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meli-api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meli-api
  template:
    metadata:
      labels:
        app: meli-api
    spec:
      containers:
      - name: meli-api
        image: k8s/meli/api:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081