on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:

    meli-api-build:
      name: meli-api Build
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Connect to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Build and push image to AWS ECR
        id: build-image
        working-directory: ./meli-api
        run: |
          sudo chmod +x build.sh
          ./build.sh
  
  